project: 
  output-dir: _output

notebook-links: global

execute:
  freeze: auto

crossref:
  custom:
    - kind: float
      reference-prefix: Document
      key: doc
      latex-env: docu

number-sections: true

metadata-files:
  - metadata/_oules.yml
  - metadata/_wissel.yml
  - metadata/_html.yml
  - metadata/_pdf.yml